// Ported from InsightCompanion.reference.tsx — frame engine, blink loop,
// SETS/TOPICS tables, and the halftone-sprite JSX are unchanged. Only
// handleSubmit/the old typeText loop were replaced with a real streamed
// call to /api/companion, which tags its own topic as the first line.
// Sprite PNGs live at /public/sprites/{idle1,idle2,idle3,blink,talk1,talk2,talk3}.png
// (generated by scripts/make_sprite_frames.py).

"use client";
import { useEffect, useRef, useState } from "react";

const SPRITE = (name: string) => `/sprites/${name}.png`;

const SETS = {
  idle:  { frames: [SPRITE("idle1"), SPRITE("idle2"), SPRITE("idle1"), SPRITE("idle3")], interval: 150 },
  chill: { frames: [SPRITE("idle1"), SPRITE("idle3"), SPRITE("idle3"), SPRITE("idle1"), SPRITE("idle2"), SPRITE("idle1")], interval: 230 },
  talkUrgent:  { frames: [SPRITE("talk1"), SPRITE("talk2"), SPRITE("talk3"), SPRITE("talk2"), SPRITE("talk1"), SPRITE("talk3")], interval: 95 },
  talkCalm:    { frames: [SPRITE("talk1"), SPRITE("talk3"), SPRITE("talk1"), SPRITE("talk2")], interval: 170 },
  talkNeutral: { frames: [SPRITE("talk1"), SPRITE("talk2"), SPRITE("talk1"), SPRITE("talk3")], interval: 130 },
} as const;

type SetKey = keyof typeof SETS;

const TOPICS = {
  workload: { accent: "#c45a2a", glyph: "!",  set: "talkUrgent" as SetKey, border: "#c45a2a", shadow: "0 0 10px rgba(196,90,42,0.30)" },
  budget:   { accent: "#e8dfc9", glyph: "?",  set: "talkCalm" as SetKey,   border: "#6e665a", shadow: "none" },
  schedule: { accent: "#e8dfc9", glyph: "?!", set: "talkNeutral" as SetKey,border: "#6e665a", shadow: "none" },
} as const;

type Topic = keyof typeof TOPICS;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export default function InsightCompanion() {
  const [spriteSrc, setSpriteSrc] = useState(SPRITE("idle1"));
  const [tag, setTag] = useState("idle");
  const [glyph, setGlyph] = useState<{ sym: string; color: string; show: boolean }>({ sym: "!", color: "#e8dfc9", show: false });
  const [bubble, setBubble] = useState<{ text: string; show: boolean; border: string; shadow: string }>({
    text: "", show: false, border: "#6e665a", shadow: "none",
  });
  const [query, setQuery] = useState("");

  // active set is a ref, not state — the frame loop reads it every tick
  // without needing to restart the effect/interval on every state change.
  const active = useRef<SetKey>("idle");
  const frameIdx = useRef(0);
  const setActive = (key: SetKey) => { active.current = key; frameIdx.current = 0; };

  // continuous frame engine
  useEffect(() => {
    let alive = true;
    (async () => {
      while (alive) {
        const set = SETS[active.current];
        setSpriteSrc(set.frames[frameIdx.current % set.frames.length]);
        frameIdx.current++;
        await sleep(set.interval);
      }
    })();
    return () => { alive = false; };
  }, []);

  // independent involuntary blink
  useEffect(() => {
    let alive = true;
    (async () => {
      while (alive) {
        await sleep(2800 + Math.random() * 3200);
        setSpriteSrc(SPRITE("blink"));
        await sleep(90);
        // next frame-engine tick overwrites this naturally
      }
    })();
    return () => { alive = false; };
  }, []);

  async function flashGlyph(sym: string, color: string, dur: number) {
    setGlyph({ sym, color, show: true });
    await sleep(dur);
    setGlyph((g) => ({ ...g, show: false }));
  }

  async function idlePhase() {
    const chilling = Math.random() < 0.4;
    setTag(chilling ? "chilling" : "idle");
    setActive(chilling ? "chill" : "idle");
    await sleep(chilling ? 3200 : 1600 + Math.random() * 900);
  }

  // Streams the reply from /api/companion. The model tags its own topic as
  // a leading {"topic":"..."} line — buffered until the first newline,
  // then everything after that line is the real message, typed into the
  // bubble as tokens actually arrive (no simulated per-character delay).
  async function talkPhaseStream(question: string) {
    setTag("talking");
    setActive("idle");
    await flashGlyph("...", "#e8dfc9", 850 + Math.random() * 300);

    let raw = "";
    let topic: Topic | null = null;
    let bodyStart = 0;

    try {
      const res = await fetch("/api/companion", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mode: "query", message: question }),
      });
      if (!res.body) throw new Error("no stream");
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        raw += decoder.decode(value, { stream: true });
        if (topic === null) {
          const nl = raw.indexOf("\n");
          if (nl === -1) continue; // still buffering the tag line
          const match = raw.slice(0, nl).match(/"topic"\s*:\s*"(\w+)"/);
          topic = match && match[1] in TOPICS ? (match[1] as Topic) : "schedule";
          bodyStart = nl + 1;
          const t = TOPICS[topic];
          setTag(`talking · ${topic}`);
          setBubble((b) => ({ ...b, border: t.border, shadow: t.shadow, show: true, text: "" }));
          setActive(t.set);
        }
        setBubble((b) => ({ ...b, text: raw.slice(bodyStart) }));
      }
    } catch {
      setBubble((b) => ({ ...b, show: true, text: "connection dropped." }));
    }

    const resolved = topic ?? "schedule";
    const t = TOPICS[resolved];
    await sleep(2500);

    setBubble((b) => ({ ...b, show: false }));
    setActive("idle");
    await sleep(400);
    await flashGlyph(t.glyph, t.accent, 700);
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!query.trim()) return;
    const q = query.trim();
    setQuery("");
    await talkPhaseStream(q);
  }

  return (
    <div style={{
      width: 320, height: "100vh", position: "relative",
      fontFamily: "'Courier New', monospace", color: "#e8dfc9",
      background: "#0d0c0a", borderRight: "1px solid #232018", overflow: "hidden",
    }}>
      <div style={{ position: "absolute", top: 14, left: 14, fontSize: 11, color: "#4a4437", letterSpacing: 1 }}>
        / COMPANION
      </div>
      <div style={{ position: "absolute", top: 14, right: 14, fontSize: 10, color: "#4a4437", letterSpacing: 1, textTransform: "uppercase" }}>
        {tag}
      </div>

      <div style={{
        position: "absolute", left: 22, bottom: 330, fontSize: 20,
        color: glyph.color, opacity: glyph.show ? 1 : 0, transition: "opacity .35s ease",
      }}>
        {glyph.sym}
      </div>

      <div style={{
        position: "absolute", left: 20, bottom: 350, maxWidth: 250, minHeight: 20,
        border: `1px solid ${bubble.border}`, boxShadow: bubble.shadow, padding: 12,
        fontSize: 13, lineHeight: 1.6, whiteSpace: "pre-wrap",
        opacity: bubble.show ? 1 : 0, transition: "opacity .4s ease, border-color .3s ease, box-shadow .3s ease",
      }}>
        {bubble.text}
      </div>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={spriteSrc}
        alt=""
        style={{ position: "absolute", left: 14, bottom: 90, width: 220, imageRendering: "pixelated" }}
      />

      <div style={{ position: "absolute", bottom: 60, left: 20, right: 20, borderTop: "1px dotted #6e665a" }} />

      <form onSubmit={handleSubmit} style={{ position: "absolute", bottom: 24, left: 24, right: 24 }}>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="> ask something..."
          style={{
            background: "transparent", border: "none", outline: "none", width: "100%",
            fontFamily: "'Courier New', monospace", fontSize: 13, color: "#e8dfc9",
          }}
        />
      </form>
    </div>
  );
}
