// Ported from InsightCompanion.reference.tsx — frame engine, blink loop,
// SETS/TOPICS tables, and the halftone-sprite JSX are unchanged. Only
// handleSubmit/the old typeText loop were replaced with a real streamed
// call to /api/companion, which tags its own topic as the first line.
// Sprite PNGs live at /public/sprites/{idle1,idle2,idle3,blink,talk1,talk2,talk3}.png
// (generated by scripts/make_sprite_frames.py).

"use client";
import { useEffect, useRef, useState } from "react";

const SPRITE = (name: string) => `/sprites/${name}.png`;

const SETS = {
  idle:  { frames: [SPRITE("idle1"), SPRITE("idle2"), SPRITE("idle1"), SPRITE("idle3")], interval: 150 },
  chill: { frames: [SPRITE("idle1"), SPRITE("idle3"), SPRITE("idle3"), SPRITE("idle1"), SPRITE("idle2"), SPRITE("idle1")], interval: 230 },
  talkUrgent:  { frames: [SPRITE("talk1"), SPRITE("talk2"), SPRITE("talk3"), SPRITE("talk2"), SPRITE("talk1"), SPRITE("talk3")], interval: 95 },
  talkCalm:    { frames: [SPRITE("talk1"), SPRITE("talk3"), SPRITE("talk1"), SPRITE("talk2")], interval: 170 },
  talkNeutral: { frames: [SPRITE("talk1"), SPRITE("talk2"), SPRITE("talk1"), SPRITE("talk3")], interval: 130 },
} as const;

type SetKey = keyof typeof SETS;

const TOPICS = {
  workload: { accent: "#c45a2a", glyph: "!",  set: "talkUrgent" as SetKey, border: "#c45a2a", shadow: "0 0 10px rgba(196,90,42,0.30)" },
  budget:   { accent: "#e8dfc9", glyph: "?",  set: "talkCalm" as SetKey,   border: "#6e665a", shadow: "none" },
  schedule: { accent: "#e8dfc9", glyph: "?!", set: "talkNeutral" as SetKey,border: "#6e665a", shadow: "none" },
} as const;

type Topic = keyof typeof TOPICS;

// Temporary, session-only scrollback — the last few exchanges (yours and
// the companion's unprompted asides) stay visible above the sprite
// instead of a single bubble that fades a few seconds after typing.
type Exchange = { id: number; you: string; text: string; border: string; shadow: string; done: boolean };
const MAX_HISTORY = 6;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// Same diagonal-cut corner the dashboard's own panels use (see
// lib/theme.ts's notch()) — reproduced locally since this component is
// intentionally self-contained/inline-styled.
const notch = (size = 8) =>
  `polygon(0 0, calc(100% - ${size}px) 0, 100% ${size}px, 100% 100%, 0 100%)`;

export default function InsightCompanion() {
  const [spriteSrc, setSpriteSrc] = useState(SPRITE("idle1"));
  const [tag, setTag] = useState("idle");
  const [glyph, setGlyph] = useState<{ sym: string; color: string; show: boolean }>({ sym: "!", color: "#e8dfc9", show: false });
  // The current reply lives in `activeMsg` — a single prominent bubble
  // right above the sprite. Once it's held on screen a while, it graduates
  // into `history` (smaller, muted, scrollable) and activeMsg clears.
  const [activeMsg, setActiveMsg] = useState<Exchange | null>(null);
  const [history, setHistory] = useState<Exchange[]>([]);
  const [query, setQuery] = useState("");
  const historyRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = historyRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [history]);

  // active set is a ref, not state — the frame loop reads it every tick
  // without needing to restart the effect/interval on every state change.
  const active = useRef<SetKey>("idle");
  const frameIdx = useRef(0);
  const setActive = (key: SetKey) => { active.current = key; frameIdx.current = 0; };
  const busy = useRef(false); // true while a reply (asked or ambient) is in flight

  // continuous frame engine
  useEffect(() => {
    let alive = true;
    (async () => {
      while (alive) {
        const set = SETS[active.current];
        setSpriteSrc(set.frames[frameIdx.current % set.frames.length]);
        frameIdx.current++;
        await sleep(set.interval);
      }
    })();
    return () => { alive = false; };
  }, []);

  // independent involuntary blink
  useEffect(() => {
    let alive = true;
    (async () => {
      while (alive) {
        await sleep(2800 + Math.random() * 3200);
        setSpriteSrc(SPRITE("blink"));
        await sleep(90);
        // next frame-engine tick overwrites this naturally
      }
    })();
    return () => { alive = false; };
  }, []);

  async function flashGlyph(sym: string, color: string, dur: number) {
    setGlyph({ sym, color, show: true });
    await sleep(dur);
    setGlyph((g) => ({ ...g, show: false }));
  }

  async function idlePhase() {
    const chilling = Math.random() < 0.4;
    setTag(chilling ? "chilling" : "idle");
    setActive(chilling ? "chill" : "idle");
    await sleep(chilling ? 3200 : 1600 + Math.random() * 900);
  }

  // Streams the reply from /api/companion. The model tags its own topic as
  // a leading {"topic":"..."} line — buffered until the first newline,
  // then everything after that line is the real message, typed into the
  // single active bubble as tokens actually arrive (no simulated per-char
  // delay). Once done, it lingers there, then graduates into `history`.
  async function talkPhaseStream(question: string, you: string) {
    busy.current = true;
    setTag("talking");
    setActive("idle");
    await flashGlyph("...", "#e8dfc9", 850 + Math.random() * 300);

    let raw = "";
    let topic: Topic | null = null;
    let bodyStart = 0;
    let errored = false;
    const id = Date.now();

    try {
      const res = await fetch("/api/companion", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mode: "query", message: question }),
      });
      if (!res.body) throw new Error("no stream");
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        raw += decoder.decode(value, { stream: true });
        if (topic === null) {
          const nl = raw.indexOf("\n");
          if (nl === -1) continue; // still buffering the tag line
          const match = raw.slice(0, nl).match(/"topic"\s*:\s*"(\w+)"/);
          topic = match && match[1] in TOPICS ? (match[1] as Topic) : "schedule";
          bodyStart = nl + 1;
          const t = TOPICS[topic];
          setTag(`talking · ${topic}`);
          setActive(t.set);
          setActiveMsg({ id, you, text: "", border: t.border, shadow: t.shadow, done: false });
        }
        const text = raw.slice(bodyStart);
        setActiveMsg((m) => (m && m.id === id ? { ...m, text } : m));
      }
    } catch {
      errored = true;
    }

    const resolved = topic ?? "schedule";
    const t = TOPICS[resolved];
    const finalText = errored ? "connection dropped." : raw.slice(bodyStart) || "...";
    const finished: Exchange = { id, you, text: finalText, border: t.border, shadow: t.shadow, done: true };
    setActiveMsg(finished);
    setActive("idle");

    await sleep(2500); // lingers as the single prominent bubble

    setActiveMsg((m) => (m && m.id === id ? null : m)); // graduate — unless a newer reply already took over
    setHistory((h) => [...h, finished].slice(-MAX_HISTORY));

    await sleep(400);
    await flashGlyph(t.glyph, t.accent, 700);
    busy.current = false;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!query.trim() || busy.current) return;
    const q = query.trim();
    setQuery("");
    await talkPhaseStream(q, q);
  }

  // Every few minutes, unprompted, glance at the dashboard and say
  // something about it — reuses the exact same streamed reply + topic
  // tagging as a real question, just with a self-generated prompt.
  useEffect(() => {
    let alive = true;
    let timer: ReturnType<typeof setTimeout>;
    const loop = () => {
      timer = setTimeout(async () => {
        if (!alive) return;
        if (!busy.current) {
          await talkPhaseStream(
            "(unprompted aside — don't wait for me to ask) Glance at my dashboard and say one short, playful thing about whatever stands out right now: a deadline, my balance, today's schedule, anything.",
            ""
          );
        }
        if (alive) loop();
      }, 150000 + Math.random() * 180000); // every ~2.5-5.5 min
    };
    loop();
    return () => { alive = false; clearTimeout(timer); };
  }, []);

  return (
    <div style={{
      width: "100%", height: "100%", position: "relative",
      fontFamily: "'Courier New', monospace", color: "#e8dfc9",
      background: "transparent", overflow: "hidden", pointerEvents: "none",
    }}>
      <div style={{ position: "absolute", top: 14, left: 14, fontSize: 11, color: "#4a4437", letterSpacing: 1 }}>
        / COMPANION
      </div>
      <div style={{ position: "absolute", top: 14, right: 14, fontSize: 10, color: "#4a4437", letterSpacing: 1, textTransform: "uppercase" }}>
        {tag}
      </div>

      <div style={{
        position: "absolute", left: 22, bottom: 330, fontSize: 20,
        color: glyph.color, opacity: glyph.show ? 1 : 0, transition: "opacity .35s ease",
      }}>
        {glyph.sym}
      </div>

      {/* One flex column, bottom-anchored just above the sprite, so a
          single bubble sits right above her by default. Older,
          "graduated" exchanges (muted, capped height, own scroll) stack
          above the current one instead of overlapping it. */}
      <div style={{
        position: "absolute", left: 16, right: 16, top: 46, bottom: 330,
        display: "flex", flexDirection: "column", justifyContent: "flex-end", gap: 12,
        pointerEvents: "auto",
      }}>
        {history.length > 0 && (
          <div
            ref={historyRef}
            className="hud-scroll"
            style={{
              // justify-content:flex-end on a scrolling flex container clips
              // content pushed above the top instead of making it scrollable
              // (scrollTop can't go negative) — plain top-to-bottom flow plus
              // the scrollTop-to-bottom effect below is the correct pattern.
              maxHeight: 200, overflowY: "auto", display: "flex", flexDirection: "column",
              gap: 8, opacity: 0.6, flexShrink: 0,
            }}
          >
            {history.map((ex) => (
              <div key={ex.id}>
                {ex.you && (
                  <div style={{ fontSize: 10, color: "#4a4437", textAlign: "right", marginBottom: 2 }}>
                    &gt; {ex.you}
                  </div>
                )}
                <div style={{
                  border: `1px solid ${ex.border}`, clipPath: notch(6), padding: 8,
                  fontSize: 12, lineHeight: 1.5, whiteSpace: "pre-wrap",
                }}>
                  {ex.text}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* The current reply — a single prominent bubble. Lingers here,
            then talkPhaseStream graduates it into the scrollback above. */}
        {activeMsg && (
          <div style={{ flexShrink: 0 }}>
            {activeMsg.you && (
              <div style={{ fontSize: 11, color: "#6e665a", textAlign: "right", marginBottom: 4 }}>
                &gt; {activeMsg.you}
              </div>
            )}
            <div style={{
              border: `1px solid ${activeMsg.border}`, clipPath: notch(10), boxShadow: activeMsg.shadow, padding: 12,
              fontSize: 13, lineHeight: 1.6, whiteSpace: "pre-wrap",
            }}>
              {activeMsg.text}
              {!activeMsg.done && <span style={{ color: activeMsg.border }}>▋</span>}
            </div>
            {/* speech-bubble tail, pointing down toward the sprite */}
            <div style={{
              width: 0, height: 0, marginLeft: 18,
              borderLeft: "6px solid transparent", borderRight: "6px solid transparent",
              borderTop: `7px solid ${activeMsg.border}`,
            }} />
          </div>
        )}
      </div>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={spriteSrc}
        alt=""
        style={{ position: "absolute", left: 14, bottom: 90, width: 220, imageRendering: "pixelated" }}
      />

      <div style={{ position: "absolute", bottom: 60, left: 20, right: 20, borderTop: "1px dotted #6e665a" }} />

      <form onSubmit={handleSubmit} style={{ position: "absolute", bottom: 24, left: 24, right: 24, pointerEvents: "auto" }}>
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="> ask something..."
          style={{
            background: "transparent", border: "none", outline: "none", width: "100%",
            fontFamily: "'Courier New', monospace", fontSize: 13, color: "#e8dfc9",
          }}
        />
      </form>
    </div>
  );
}
